# Generated by Django 5.2.5 on 2025-08-10 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliodashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='date',
        ),
    ]
